CREATE TABLE ERR_LOG
  (
    ID_ERR_LOG       NUMBER NOT NULL ,
    ERR_LOG_FUNCTION VARCHAR2 (1000) NOT NULL ,
    ERR_LOG_TEXT CLOB NOT NULL ,
    ERR_LOG_DATE DATE NOT NULL ,
    ID_USR       NUMBER ,
    APP_ID       NUMBER ,
    APP_PAGE_ID  NUMBER
  ) ;
CREATE INDEX I_ERR_LOG_ERR_LOG_DATE ON ERR_LOG
  ( ERR_LOG_DATE ASC
  ) ;
CREATE INDEX I_ERR_LOG_APP_ID ON ERR_LOG
  ( APP_ID ASC
  ) ;
ALTER TABLE ERR_LOG ADD CONSTRAINT PK_ERR_LOG PRIMARY KEY ( ID_ERR_LOG ) ;
