 CREATE TABLE PUB_THEMES
  (
    ID_PUB_THEMES NUMBER NOT NULL         ,
    ID_USR        NUMBER NOT NULL         ,
    THEME_NAME    VARCHAR2 (200) NOT NULL ,
    PREVIEW_IMG CLOB NOT NULL             ,
    GAME_DAYMODE         VARCHAR2 (100) NOT NULL  ,
    GAME_BIRD_COLOR      VARCHAR2 (100) NOT NULL  ,
    GAME_TREETOP_COLOR   VARCHAR2 (100) NOT NULL  ,
    GAME_TREETRUNK_COLOR VARCHAR2 (100) NOT NULL  ,
    GAME_BOTTOM_COLOR    VARCHAR2 (100) NOT NULL  ,
    GAME_GRASS_COLOR     VARCHAR2 (100) NOT NULL  ,
    GAME_BAR_COLOR       VARCHAR2 (100) NOT NULL
  ) ;
 CREATE INDEX I_PUB_THEMES_ID_USR ON PUB_THEMES
  (
    ID_USR ASC
  ) ;
ALTER TABLE PUB_THEMES ADD CONSTRAINT PK_PUB_THEMES PRIMARY KEY ( ID_PUB_THEMES
) ;
