CREATE TABLE SYSTEM
  (
    ID_SYSTEM               NUMBER NOT NULL ,
    TWITTER_CONSUMER_KEY    VARCHAR2 (500) ,
    TWITTER_CONSUMER_SECRET VARCHAR2 (500) ,
    TWITTER_API_BEARER      VARCHAR2 (500) ,
    TWITTER_SSL_WALLET_PATH VARCHAR2 (200) ,
    TWITTER_SSL_WALLET_PWD  VARCHAR2 (500) ,
    EMAIL_FROM              VARCHAR2 (100) ,
    EMAIL_REGISTER_SUBJECT  VARCHAR2 (200) ,
    EMAIL_REGISTER_TEXT CLOB ,
    EMAIL_USRPWD_SUBJECT VARCHAR2 (200) ,
    EMAIL_USRPWD_TEXT CLOB
  ) ;
ALTER TABLE SYSTEM ADD CONSTRAINT PK_SYSTEM PRIMARY KEY ( ID_SYSTEM ) ;
