  ALTER TABLE USR_LOCATION ADD CONSTRAINT FK_USR_LOCATION_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_PREFS ADD CONSTRAINT FK_USR_PREFS_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_TOKEN ADD CONSTRAINT FK_USR_TOKEN_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_TW_FRIENDS ADD CONSTRAINT FK_USR_TW_FRIENDS_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  