  ALTER TABLE USR_LOCATION ADD CONSTRAINT FK_USR_LOCATION_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_PREFS ADD CONSTRAINT FK_USR_PREFS_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_TOKEN ADD CONSTRAINT FK_USR_TOKEN_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_TW_FRIENDS ADD CONSTRAINT FK_USR_TW_FRIENDS_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE PUB_THEMES ADD CONSTRAINT FK_PUB_THEMES_ID_USR FOREIGN KEY ( ID_USR ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_BATTLE ADD CONSTRAINT FK_USR_BATTLE_ID_USR_CHALL FOREIGN KEY ( ID_USR_CHALLENGER ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  ALTER TABLE USR_BATTLE ADD CONSTRAINT FK_USR_BATTLE_ID_USR_REC FOREIGN KEY ( ID_USR_RECEIVER ) REFERENCES USR ( ID_USR ) ON
  DELETE CASCADE ;
  