CREATE TABLE USR_TW_FRIENDS
  (
    ID_USR_TW_FRIENDS     NUMBER NOT NULL ,
    ID_USR                NUMBER NOT NULL ,
    ID_USR_FRIEND         NUMBER ,
    USR_FRIEND_TWITTER_ID NUMBER
  ) ;
CREATE INDEX I_USR_TW_FRIENDS_ID_USR ON USR_TW_FRIENDS
  ( ID_USR ASC
  ) ;
ALTER TABLE USR_TW_FRIENDS ADD CONSTRAINT PK_USR_TW_FRIENDS PRIMARY KEY ( ID_USR_TW_FRIENDS ) ;