CREATE TABLE USR_PREFS
  (
    ID_USR_PREFS         NUMBER NOT NULL ,
    ID_USR               NUMBER NOT NULL ,
    GAME_DAYMODE         VARCHAR2 (100) ,
    GAME_BIRD_COLOR      VARCHAR2 (100) ,
    GAME_TREETOP_COLOR   VARCHAR2 (100) ,
    GAME_TREETRUNK_COLOR VARCHAR2 (100) ,
    GAME_BOTTOM_COLOR    VARCHAR2 (100) ,
    GAME_GRASS_COLOR     VARCHAR2 (100) ,
    GAME_BAR_COLOR       VARCHAR2 (100)
  ) ;
CREATE INDEX I_USR_PREFS_ID_USR ON USR_PREFS
  ( ID_USR ASC
  ) ;
ALTER TABLE USR_PREFS ADD CONSTRAINT PK_USR_PREFS PRIMARY KEY ( ID_USR_PREFS ) ;
