CREATE TABLE USR_TOKEN
  (
    ID_USR_TOKEN NUMBER NOT NULL ,
    ID_USR       NUMBER NOT NULL ,
    TOKEN        VARCHAR2 (500) NOT NULL ,
    TOKEN_DATE   DATE NOT NULL
  ) ;
CREATE INDEX I_USR_TOKEN_ID_USR ON USR_TOKEN
  ( ID_USR ASC
  ) ;
CREATE INDEX I_USR_TOKEN_TOKEN_DATE ON USR_TOKEN
  ( TOKEN_DATE ASC
  ) ;
ALTER TABLE USR_TOKEN ADD CONSTRAINT PK_USR_TOKEN PRIMARY KEY ( ID_USR_TOKEN ) ;
