CREATE TABLE USR_LOCATION
  (
    ID_USR_LOCATION NUMBER NOT NULL ,
    ID_USR          NUMBER NOT NULL ,
    GEO_LATITUDE    NUMBER NOT NULL ,
    GEO_LONGITUDE   NUMBER NOT NULL
  ) ;
CREATE INDEX I_USR_LOCATION_ID_USR ON USR_LOCATION
  ( ID_USR ASC
  ) ;
CREATE INDEX I_USR_LOCATION_LATITUDE ON USR_LOCATION
  ( GEO_LATITUDE ASC
  ) ;
CREATE INDEX I_USR_LOCATION_LONGITUDE ON USR_LOCATION
  ( GEO_LONGITUDE ASC
  ) ;
ALTER TABLE USR_LOCATION ADD CONSTRAINT PK_USR_LOCATION PRIMARY KEY ( ID_USR_LOCATION ) ;
